<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\XNode.Core\XNode.Core.csproj" />
    <ProjectReference Include="..\XNode.Transport.Vless\XNode.Transport.Vless.csproj" />
    <ProjectReference Include="..\XNode.Registry\XNode.Registry.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <RestoreAdditionalProjectSources>$(MSBuildThisFileDirectory)..\..\vendor\mailbox-client-package-corrected;$(RestoreAdditionalProjectSources)</RestoreAdditionalProjectSources>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
