<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <RestoreConfigFile>$(MSBuildThisFileDirectory)..\..\eng\mailbox-client.NuGet.Config</RestoreConfigFile>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <RestoreLockedMode>true</RestoreLockedMode>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Deep.Protocol" Version="[0.3.0-p03b2.a34e726]" />
    <PackageReference Include="Deep.Protocol.MembershipRoutes" Version="[0.3.0-p03b2.a34e726]" />
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\XNode.Core\XNode.Core.csproj" />
    <ProjectReference Include="..\..\src\XNode.Transport.Vless\XNode.Transport.Vless.csproj" />
    <ProjectReference Include="..\..\src\XNode.Registry\XNode.Registry.csproj" />
  </ItemGroup>

</Project>
