<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RestoreConfigFile>$(MSBuildThisFileDirectory)..\..\eng\mailbox-client.NuGet.Config</RestoreConfigFile>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <RestoreLockedMode>true</RestoreLockedMode>
    <RuntimeIdentifiers>linux-x64;linux-arm64</RuntimeIdentifiers>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Deep.Protocol" Version="[0.3.0-p09c2.f1a93c9]" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.0" />
    <PackageReference Include="Rebex.Elliptic.Ed25519" Version="1.2.2" />
    <PackageReference Include="Sodium.Core" Version="1.4.1" />
  </ItemGroup>

</Project>
